name: Install Beachball
description: Globally installs the version of Beachball specified in the repo root package.json devDependencies
runs:
  using: composite
  steps:
    - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      with:
        script: |
          const beachballVersion = require('./package.json').devDependencies.beachball;
          if (beachballVersion) {
            console.log(`Using beachball@${beachballVersion}...`)
            await exec.exec('npm', ['i', '-g', `beachball@${beachballVersion}`]);
          } else {
            core.setFailed("Please verify that 'package.json' includes 'beachball' in 'devDependencies'")
          }
