name: batch-runs
description: Checks if newer workflow runs are pending for this branch, and (by default) cancels if so
inputs:
  token:
    description: GitHub token with "actions:write" permission
    required: true
  mode:
    description: Whether to cancel the run ("cancel") or set an output variable ("output")
    default: cancel
outputs:
  shouldCancel:
    description: Whether the run should be canceled ("yes" or "no")
runs:
  using: node20
  main: dist/index.js
